---
- name: web servers update
  hosts: all
  become: yes

  tasks:
  - name: Ensure APT update
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache httpd installed
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Ensure Apache httpd installed
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

  - name: start enable the Apache2
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: start the Apache httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

  - name: enable the Apache httpd
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"
...
